# Generated by Django 2.2 on 2020-07-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_perform',
            field=models.DateField(blank=True, default='0001-01-01', null=True),
        ),
    ]
