# Generated by Django 2.2 on 2020-07-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_perform',
            field=models.DateField(default='', null=True, verbose_name='Data'),
        ),
    ]
